/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tst_project_0.pkg6_registro;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author vladi
 */
public class amministratoreRegistrazione extends javax.swing.JFrame {

    /**
     * Creates new form amministratoreRegistrazione
     */
    public amministratoreRegistrazione() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        radioM = new javax.swing.JRadioButton();
        radioF = new javax.swing.JRadioButton();
        textNome = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        textPasswordC = new javax.swing.JPasswordField();
        textNazione = new javax.swing.JTextField();
        textComune = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAltro = new javax.swing.JTextArea();
        textData = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        radioAlunno = new javax.swing.JRadioButton();
        radioProfessore = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Amministratore - Gestione Account");
        setResizable(false);

        jLabel1.setText("Nome e Cognome:*");

        jLabel2.setText("Password:*");

        jLabel3.setText("Ripeti Password:*");

        jLabel4.setText("Sesso:*");

        jLabel5.setText("Data di nascita:*");

        jLabel6.setText("Nazionalità:*");

        jLabel7.setText("Comune di residenza:");

        jLabel8.setText("Altre informazioni:");

        jButton1.setText("Crea Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        radioM.setText("M");
        radioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMActionPerformed(evt);
            }
        });

        radioF.setText("F");
        radioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFActionPerformed(evt);
            }
        });

        textAltro.setColumns(20);
        textAltro.setRows(5);
        jScrollPane1.setViewportView(textAltro);

        jLabel9.setText("Privilegi*:");

        radioAlunno.setText("Alunno");
        radioAlunno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlunnoActionPerformed(evt);
            }
        });

        radioProfessore.setText("Professore");
        radioProfessore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioProfessoreActionPerformed(evt);
            }
        });

        jButton2.setText("Torna al Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(textComune, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textNazione, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textPasswordC, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textNome, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioAlunno)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioProfessore))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(102, 102, 102)
                                .addComponent(radioM)
                                .addGap(18, 18, 18)
                                .addComponent(radioF)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPasswordC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(radioAlunno)
                    .addComponent(radioProfessore))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioM)
                    .addComponent(radioF)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textComune, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMActionPerformed
        // TODO add your handling code here:
        radioF.setSelected(false);
    }//GEN-LAST:event_radioMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       this.hide();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioAlunnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlunnoActionPerformed
        // TODO add your handling code here:
        radioProfessore.setSelected(false);
    }//GEN-LAST:event_radioAlunnoActionPerformed

    private void radioProfessoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioProfessoreActionPerformed
        // TODO add your handling code here:       
        radioAlunno.setSelected(false);
    }//GEN-LAST:event_radioProfessoreActionPerformed

    private void radioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFActionPerformed
radioM.setSelected(false);
    }//GEN-LAST:event_radioFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = textNome.getText();
        String password = String.valueOf(textPassword.getPassword());
        String passwordC = String.valueOf(textPasswordC.getPassword());
        String dataNascita = textData.getText();
        String comune = textComune.getText();
        String nazione = textNazione.getText(); 
        String informazioni = textAltro.getText();
        boolean text = false;
        boolean  prv = false;
        boolean sex = false;
        boolean DataPCom = false;
    if(password.equals(passwordC) && !(password.equals(""))&& !(nome.equals("")))
    {
        text = true;
    }else{
        text = false;
        JOptionPane.showMessageDialog(null,"Il nome utente o la Password non è accetta, verificare i campi");      
    }
    if(radioAlunno.isSelected() || radioProfessore.isSelected())
        {
        prv = true;
        }else{
        prv = false;
        JOptionPane.showMessageDialog(null,"Selezionare i privilegi da assegnare all'utente");      
    }
    if(radioM.isSelected() ||radioF.isSelected()){
    sex= true;
    }else{
   sex= false;
  JOptionPane.showMessageDialog(null,"Selezionare il sesso");      
    }
if(!(nazione.equals("")) && !(dataNascita.equals(""))){
 DataPCom=true;
}else{
DataPCom=false;
JOptionPane.showMessageDialog(null,"campi data di nascita o nazione non inseriti o incorretti");      
}
if(text == true && prv ==true && sex==true && DataPCom==true){
    new registrazioneSystemInfo();
    new registrazioneSystemAccount();
    new registrazionePoteri();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    public static JRadioButton getRadioAlunno() {
        return radioAlunno;
    }

    public static void setRadioAlunno(JRadioButton radioAlunno) {
        amministratoreRegistrazione.radioAlunno = radioAlunno;
    }

    public static JRadioButton getRadioM() {
        return radioM;
    }

    public static void setRadioM(JRadioButton radioM) {
        amministratoreRegistrazione.radioM = radioM;
    }

    public static JRadioButton getRadioProfessore() {
        return radioProfessore;
    }

    public static void setRadioProfessore(JRadioButton radioProfessore) {
        amministratoreRegistrazione.radioProfessore = radioProfessore;
    }

    public static JTextArea getTextAltro() {
        return textAltro;
    }

    public static void setTextAltro(JTextArea textAltro) {
        amministratoreRegistrazione.textAltro = textAltro;
    }

    public static JTextField getTextComune() {
        return textComune;
    }

    public static void setTextComune(JTextField textComune) {
        amministratoreRegistrazione.textComune = textComune;
    }

    public static JTextField getTextData() {
        return textData;
    }

    public static void setTextData(JTextField textData) {
        amministratoreRegistrazione.textData = textData;
    }

    public static JTextField getTextNazione() {
        return textNazione;
    }

    public static void setTextNazione(JTextField textNazione) {
        amministratoreRegistrazione.textNazione = textNazione;
    }

    public static JTextField getTextNome() {
        return textNome;
    }

    public static void setTextNome(JTextField textNome) {
        amministratoreRegistrazione.textNome = textNome;
    }

    public static JPasswordField getTextPassword() {
        return textPassword;
    }

    public static void setTextPassword(JPasswordField textPassword) {
        amministratoreRegistrazione.textPassword = textPassword;
    }

    public static JPasswordField getTextPasswordC() {
        return textPasswordC;
    }

    public static void setTextPasswordC(JPasswordField textPasswordC) {
        amministratoreRegistrazione.textPasswordC = textPasswordC;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amministratoreRegistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amministratoreRegistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amministratoreRegistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amministratoreRegistrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amministratoreRegistrazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton radioAlunno;
    public static javax.swing.JRadioButton radioF;
    public static javax.swing.JRadioButton radioM;
    public static javax.swing.JRadioButton radioProfessore;
    public static javax.swing.JTextArea textAltro;
    public static javax.swing.JTextField textComune;
    public static javax.swing.JTextField textData;
    public static javax.swing.JTextField textNazione;
    public static javax.swing.JTextField textNome;
    public static javax.swing.JPasswordField textPassword;
    public static javax.swing.JPasswordField textPasswordC;
    // End of variables declaration//GEN-END:variables
}
